<a href="https://colab.research.google.com/github/Tio-Ruslanto/Tugas-Agoritma-Pemrograman/blob/main/Tugas%202%20_Alpro_Tio%20Ruslanto_3338260019.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NO 1

In [ ]:

find_median <- function(x) {
  x <- sort(x)
  n <- length(x)

  if (n %% 2 == 1) {
    median <- x[(n + 1) / 2]
  } else {
    median <- (x[n / 2] + x[n / 2 + 1]) / 2
  }

  return(median)
}

x <- c(3, 7, 2, 9, 5)
find_median(x)

[1] 5

In [ ]:
x <- c(8, 9, 5, 12, 20, 15)
find_median(x)

[1] 10.5

NO 2

In [ ]:
mean_extend <- function(x) {
  while (length(x) < 10) {
    mean_x <- sum(x) / length(x)
    x <- c(x, mean_x)

    print(x)
    print(mean_x)
  }

  return(x)
}

x <- c(3, 4, 5, 6)
mean_extend(x)

[1] 3.0 4.0 5.0 6.0 4.5
[1] 4.5
[1] 3.0 4.0 5.0 6.0 4.5 4.5
[1] 4.5
[1] 3.0 4.0 5.0 6.0 4.5 4.5 4.5
[1] 4.5
[1] 3.0 4.0 5.0 6.0 4.5 4.5 4.5 4.5
[1] 4.5
[1] 3.0 4.0 5.0 6.0 4.5 4.5 4.5 4.5 4.5
[1] 4.5
 [1] 3.0 4.0 5.0 6.0 4.5 4.5 4.5 4.5 4.5 4.5
[1] 4.5

 [1] 3.0 4.0 5.0 6.0 4.5 4.5 4.5 4.5 4.5 4.5

In [ ]:
x <- c(9, 10, 6, 12, 8, 8)
mean_extend(x)

[1]  9.000000 10.000000  6.000000 12.000000  8.000000  8.000000  8.833333
[1] 8.833333
[1]  9.000000 10.000000  6.000000 12.000000  8.000000  8.000000  8.833333
[8]  8.833333
[1] 8.833333
[1]  9.000000 10.000000  6.000000 12.000000  8.000000  8.000000  8.833333
[8]  8.833333  8.833333
[1] 8.833333
 [1]  9.000000 10.000000  6.000000 12.000000  8.000000  8.000000  8.833333
 [8]  8.833333  8.833333  8.833333
[1] 8.833333

 [1]  9.000000 10.000000  6.000000 12.000000  8.000000  8.000000  8.833333
 [8]  8.833333  8.833333  8.833333

NO 3

In [ ]:
hitung_genap <- function(x) {
  jumlah <- 0

  for (i in x) {
    if (i %% 2 == 0) {
      jumlah <- jumlah + 1
    }
  }

  return(jumlah)
}

x <- c(3, 4, 7, 10, 12, 15)
hitung_genap(x)

[1] 3

In [ ]:
x <- c(8, 8, 10, 9, 5, 100, 3)
hitung_genap(x)

[1] 4

NO 4

In [ ]:
hitung_genap_matriks <- function(m) {
  jumlah <- 0

  for (i in 1:nrow(m)) {
    for (j in 1:ncol(m)) {
      if (m[i, j] %% 2 == 0) {
        jumlah <- jumlah + m[i, j]
      }
    }
  }

  return(jumlah)
}

m <- matrix(1:12, nrow = 3, ncol = 4)

m

hitung_genap_matriks(m)

     [,1] [,2] [,3] [,4]
[1,] 1    4    7    10
[2,] 2    5    8    11
[3,] 3    6    9    12

[1] 42

In [ ]:
m <- matrix(2:22, nrow = 4, ncol = 5)
m
hitung_genap_matriks(m)

Warning message in matrix(2:22, nrow = 4, ncol = 5):
“data length [21] is not a sub-multiple or multiple of the number of rows [4]”

     [,1] [,2] [,3] [,4] [,5]
[1,] 2    6    10   14   18
[2,] 3    7    11   15   19
[3,] 4    8    12   16   20
[4,] 5    9    13   17   21

[1] 110